/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "md5.h"
#include <Android/log.h>

/* Header for class name_arche_apiencryption_EncryptionClient */

#define TAG "EncryptionClient"

#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,TAG ,__VA_ARGS__) // 定义LOGD类型
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG ,__VA_ARGS__) // 定义LOGI类型
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN,TAG ,__VA_ARGS__) // 定义LOGW类型
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG ,__VA_ARGS__) // 定义LOGE类型
#define LOGF(...) __android_log_print(ANDROID_LOG_FATAL,TAG ,__VA_ARGS__) // 定义LOGF类型

#define SALT "#sign_key"


#ifndef _Included_name_arche_apiencryption_EncryptionClient
#define _Included_name_arche_apiencryption_EncryptionClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_arche_apiencryption_EncryptionClient
 * Method:    signWithSalt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_name_arche_apiencryption_EncryptionClient_signWithSalt
  (JNIEnv * env, jclass clazz, jstring jstr){
	const char *sourceStr = (*env)->GetStringUTFChars(env, jstr, 0);
	char *sourceStrWithSalt = join(sourceStr, SALT);
	(*env)->ReleaseStringUTFChars(env, jstr, sourceStr);
	unsigned char digest[16], digestHex[33];
	memset(digestHex,0,33);
	MD5_CTX md5;
	MD5Init(&md5);
	MD5UpdaterString(&md5, sourceStrWithSalt);
	MD5Final(digest, &md5);
	ByteToHexStr(digest, digestHex, 16);
	free(sourceStrWithSalt);
	LOGD("sign: %s",digestHex);
	return (*env)->NewStringUTF(env, digestHex);
  }

#ifdef __cplusplus
}
#endif
#endif
