/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_arche_apiencryption_EncryptionClient */

#ifndef _Included_name_arche_apiencryption_EncryptionClient
#define _Included_name_arche_apiencryption_EncryptionClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_arche_apiencryption_EncryptionClient
 * Method:    signWithSalt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_name_arche_apiencryption_EncryptionClient_signWithSalt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
